project:
  type: website
  output-dir: docs/
  preview:
    browser: true
    port: 3267

website:
  title: "courtneyarmour.github.io"
  favicon: "images/c.png"
  navbar:
    background: primary
    search: true
    right:
      - text: About
        href: index.qmd
      - text: CV
        href: "cv/index.qmd"
      - text: Contact
        href: contact.qmd

format:
  html:
    theme:
      light: flatly
      dark: slate
    css: styles.css
    toc: true



